### ISSUE TITLE
Conversion of SELECT SINGLE adds second FIELDS attribute

### ISSUE THREAD

**Issue by FD1899** [lc-leuc/ABAPQuickFixS4Conversion#6]
Hello,

thanks for your excellent work!

The QuickFix for converting the SELECT SINGLE statement adds an additional FIELDS attribute, which then always has to be deleted manually. Installed version is: 1.4.1.202212211855

Kind regards,
Frank

**Comment by lc-leuc** [comment]
Hi Frank,

thanks for this finding. Could you provide an example snipplet for this? 
Also, which (target) style do you use (Settings: _Use new style (2021)_)? 

Thanks, Lawrence

**Comment by FD1899** [comment]
> Hi Frank,
> 
> thanks for this finding. Could you provide an example snipplet for this? Also, which (target) style do you use (Settings: _Use new style (2021)_)?
> 
> Thanks, Lawrence

Hi Lawrence,

I'm using the new target-style.

Here is an example:


```abap
SELECT SINGLE FROM sflight
 FIELDS *
 WHERE carrid = 'AA'
   AND connid = '0017'
   AND fldate = '20240224'
  INTO @DATA(sflight).
```
is converted to:

```abap
SELECT
  FROM sflight
  FIELDS *
  FIELDS
  where carrid = 'AA'
    AND connid = '0017'
    AND fldate = '20240224'
  ORDER BY PRIMARY KEY
  INTO @DATA(sflight)
  UP TO 1 ROWS.
ENDSELECT. 
```

Furthermore, this S4-quickfixes only working with methods but not in reports or function modules. Is there a reaseon for this behavior?

Regards, Frank

**Comment by lc-leuc** [comment]
Dear Frank,

thank you, again, for reporting and also for providing the additional information.
After looking into this, I realized that this kind of scenario was never intended (single 2021 style to select 2021 style).

However, I have included the detection of the original code style and reordered the statements.
The new version 1.4.2 also addresses some anoying problems with leading comments.

Please, check whether this version fixes your issue and let me know as soon as possible, in order to finilize the publication.

**Comment by FD1899** [comment]
Hi Lawrence, 

thank you this works fine. But can you explain, why these quickfixes doesn't work in function modules or abap reports? We have to migrate a lot of old custom code to hana conform statements and most of this is written in procedural style.

Regards Frank

**Comment by lc-leuc** [comment]
Hi Frank,

nice and thanks for verifying that the issue is solved.

Concerning the issue with classical objects: It seems that there is an issue with the dependent plugin.
I have not benn able to identify the cause exactly, however, the error messages show a OutOfBoundsException.

Best regards Lawrence

**Comment by lc-leuc** [comment]
Hi Frank (again),  

as I have filed an issue (see above) for you problem, maybe you would like to follow-up on that.

Issue is closed.

Best regards Lawrence
